name: Publishing a tagged version of SHEEP on TestPyPI

on:
  push:
    tags:
    - v*

jobs:
  pypi-publish:
    name: Publish release to TestPyPI

    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/sheep-example

    permissions:
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel build

    - name: Build package
      run: |
        python -m build

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/